// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("WordTester")>]
[<assembly: AssemblyProductAttribute("WordTester")>]
[<assembly: AssemblyDescriptionAttribute("A tool to help reading words")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "WordTester"
    let [<Literal>] AssemblyProduct = "WordTester"
    let [<Literal>] AssemblyDescription = "A tool to help reading words"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
